export default {
  id: "ships",
  title: "LR Ships",
  subtitle:
    "Basado en LR Pt 5, Ch 12, 2.12 Other mechanical couplings. Tablas 12.2.8 y 12.2.9.",
  CLASS_LIMITS: null,
  TABLE_NOTES_ES: {
    "1": "Aplicar ensayo de resistencia al fuego cuando las juntas mecánicas se instalan en salas de bombas y cubiertas abiertas.",
    "2": "Las juntas slip-on no se aceptan dentro de espacios de máquinas de categoría A ni alojamientos. Pueden aceptarse en otros espacios de máquinas si están en posiciones visibles y accesibles (MSC/Circ.734).",
    "3": "Las juntas mecánicas deben ser de tipos resistentes al fuego aprobados, salvo cuando se instalan en cubiertas abiertas según SOLAS II-2/9.2.3.3.2.2(10), y no sean usadas para líneas de fuel oil.",
    "4": "Aplicar ensayo de resistencia al fuego cuando las juntas mecánicas se instalan dentro de espacios de máquinas de categoría A.",
    "5": "Solo por encima de la cubierta de mamparo de buques de pasaje.",
    "6": "Las juntas slip type (slip-on) como en Fig. 12.2.4/12.2.5 pueden usarse en tuberías en cubierta con presión de diseño ≤ 10 bar.",
    "7": "Equivalencia de ensayos: si pasa '30 min dry' sirve también para '8 min dry + 22 min wet' y/o '30 min wet'. Si pasa '8+22', sirve para '30 min wet'.",
    "8": "Ver Pt 5, Ch 12, 2.12.10. Para CO₂ en espacio protegido: materiales con punto de fusión > 925 °C (FSS Code, Cap. 5).",
  },
  LR_REQUIREMENTS_ES: [
    { id: "2.12.1", text: "Uniones roscadas, acoples de compresión y slip-on pueden usarse si están Type Approved para el servicio y aplicación; la aprobación se basa en ensayos del propio modelo. Uso aceptable por servicio: Tabla 12.2.8. Límites de dimensiones por clase: Tabla 12.2.9." },
    { id: "2.12.2", text: "Si la aplicación reduce el espesor (p. ej., anillos bite), considerar esa reducción para cumplir la presión de diseño." },
    { id: "2.12.3", text: "Los materiales de las juntas deben ser compatibles con la tubería y con los medios interno/externo." },
    { id: "2.12.4", text: "Juntas para tuberías a presión: ensayo de reventón a 4 × la presión de diseño (≥20 MPa: a considerar especialmente)." },
    { id: "2.12.5", text: "No usar juntas mecánicas en tramos conectados al costado del buque bajo cubierta de mamparo o en tanques con fluidos inflamables cuando el daño pueda causar incendio o inundación." },
    { id: "2.12.6", text: "Las juntas deben soportar presión interna/externa y operar bajo vacío en líneas de succión cuando aplique." },
    { id: "2.12.7", text: "Minimizar el número de juntas mecánicas en sistemas de fluidos inflamables. En general, bridas según norma reconocida." },
    { id: "2.12.8", text: "En general, no usar slip-on en bodegas, tanques u otros espacios de difícil acceso; dentro de tanques solo si el medio es el mismo del tanque." },
    { id: "2.12.9", text: "No se permite usar slip type slip-on como medio principal de unión, salvo para compensar deformación axial de tuberías." },
    { id: "2.12.10", text: "Slip-on restringidas permitidas en vapor, P ≤ 1 MPa, en cubiertas a la intemperie de petroleros/quimiqueros para acomodar dilatación (ver Pt 5, Ch 13, 2.7)." },
    { id: "2.12.11", text: "Juntas mecánicas a ensayar conforme al LR Type Approval Test Spec. No. 2 para las condiciones de servicio previstas." },
  ],
  GENERAL_COMMENTS: {
    slipOnInaccessible: "2.12.8: No usar slip-on en bodegas, tanques u otros espacios de difícil acceso; dentro de tanques solo si el medio coincide.",
    slipOnNotMain: "2.12.9: No se permite usar slip type slip-on como medio principal de unión, salvo para compensar deformación axial.",
    burstPressure: "2.12.4: Las juntas mecánicas deben ensayarse a 4 × la presión de diseño.",
    typeApproval: "2.12.11: Ensayos conforme al LR Type Approval Test Spec. No. 2 para las condiciones de servicio previstas.",
    hullSide: "2.12.5: Evitar juntas mecánicas en conexiones al costado bajo cubierta de mamparo o en tanques con fluidos inflamables cuando el daño pueda causar incendio/inundación.",
    steamDeck: "2.12.10: Slip-on restringidas para vapor (P ≤ 1 MPa) en cubierta a la intemperie de petroleros/quimiqueros para acomodar dilatación.",
  },
  FIRE_TEST_EQUIVALENCE: {
    "30 min dry": ["8 min dry + 22 min wet", "30 min wet"],
    "8 min dry + 22 min wet": ["30 min wet"],
  },
  SYSTEMS: [
    { id: "ff_le60_cargo_oil", group: "Flammable fluids (flash point ≤ 60°C)", system: "Cargo oil lines", allowed: { pipeUnions: true, compression: true, slipOn: true }, pipeSystemClass: "dry", fireTest: "30 min dry (*)", notes: ["Note 1"] },
    { id: "ff_le60_crude_oil_wash", group: "Flammable fluids (flash point ≤ 60°C)", system: "Crude oil washing lines", allowed: { pipeUnions: true, compression: true, slipOn: true }, pipeSystemClass: "dry", fireTest: "30 min dry (*)", notes: ["Note 1"] },
    { id: "ff_le60_vent", group: "Flammable fluids (flash point ≤ 60°C)", system: "Vent lines", allowed: { pipeUnions: true, compression: true, slipOn: true }, pipeSystemClass: "dry", fireTest: "30 min dry (*)", notes: ["Note 3"] },
    { id: "inert_effluent_water_seal", group: "Inert gas", system: "Water seal effluent lines", allowed: { pipeUnions: true, compression: true, slipOn: true }, pipeSystemClass: "wet", fireTest: "30 min wet (*)" },
    { id: "inert_effluent_scrubber", group: "Inert gas", system: "Scrubber effluent lines", allowed: { pipeUnions: true, compression: true, slipOn: true }, pipeSystemClass: "wet", fireTest: "30 min wet (*)" },
    { id: "inert_main", group: "Inert gas", system: "Main lines", allowed: { pipeUnions: true, compression: true, slipOn: true }, pipeSystemClass: "dry", fireTest: "30 min dry (*)", notes: ["Notes 1 & 2"] },
    { id: "inert_distribution", group: "Inert gas", system: "Distribution lines", allowed: { pipeUnions: true, compression: true, slipOn: true }, pipeSystemClass: "dry", fireTest: "30 min dry (*)", notes: ["Note 1"] },
    { id: "ff_gt60_cargo_oil", group: "Flammable fluids (flash point > 60°C)", system: "Cargo oil lines", allowed: { pipeUnions: true, compression: true, slipOn: true }, pipeSystemClass: "dry", fireTest: "30 min dry (*)" },
    { id: "ff_gt60_fuel_oil", group: "Flammable fluids (flash point > 60°C)", system: "Fuel oil lines", allowed: { pipeUnions: true, compression: true, slipOn: true }, pipeSystemClass: "wet", fireTest: "30 min wet (*)", notes: ["Notes 2 & 3"] },
    { id: "ff_gt60_lube_oil", group: "Flammable fluids (flash point > 60°C)", system: "Lubricating oil lines", allowed: { pipeUnions: true, compression: true, slipOn: true }, pipeSystemClass: "wet", fireTest: "30 min wet (*)", notes: ["Notes 2 & 3"] },
    { id: "ff_gt60_hydraulic_oil", group: "Flammable fluids (flash point > 60°C)", system: "Hydraulic oil lines", allowed: { pipeUnions: true, compression: true, slipOn: true }, pipeSystemClass: "wet", fireTest: "30 min wet (*)", notes: ["Notes 2 & 3"] },
    { id: "ff_gt60_thermal_oil", group: "Flammable fluids (flash point > 60°C)", system: "Thermal oil", allowed: { pipeUnions: true, compression: true, slipOn: true }, pipeSystemClass: "wet", fireTest: "30 min wet (*)", notes: ["Notes 2 & 3"] },
    { id: "sw_bilge", group: "Sea water", system: "Bilge lines", allowed: { pipeUnions: true, compression: true, slipOn: true }, pipeSystemClass: "dry/wet", fireTest: "8 min dry + 22 min wet (*)", notes: ["Note 4"] },
    { id: "sw_fire_perm", group: "Sea water", system: "Permanent water filled fire-extinguishing systems (fire main, sprinklers)", allowed: { pipeUnions: true, compression: true, slipOn: true }, pipeSystemClass: "wet", fireTest: "30 min wet (*)", notes: ["Note 3"] },
    { id: "sw_fire_nonperm", group: "Sea water", system: "Non-permanent water filled fire-extinguishing systems (foam, drencher, fire main)", allowed: { pipeUnions: true, compression: true, slipOn: true }, pipeSystemClass: "dry/wet", fireTest: "8 min dry + 22 min wet (*)", notes: ["Note 3"], remarks: "Foam systems to comply with the FSS Code." },
    { id: "sw_ballast", group: "Sea water", system: "Ballast system", allowed: { pipeUnions: true, compression: true, slipOn: true }, pipeSystemClass: "wet", fireTest: "30 min wet (*)", notes: ["Note 4"] },
    { id: "sw_cooling", group: "Sea water", system: "Cooling water system", allowed: { pipeUnions: true, compression: true, slipOn: true }, pipeSystemClass: "wet", fireTest: "30 min wet (*)", notes: ["Note 4"] },
    { id: "sw_tank_cleaning", group: "Sea water", system: "Tank cleaning services", allowed: { pipeUnions: true, compression: true, slipOn: true }, pipeSystemClass: "dry", fireTest: "Fire endurance test not required" },
    { id: "sw_non_essential", group: "Sea water", system: "Non-essential systems", allowed: { pipeUnions: true, compression: true, slipOn: true }, pipeSystemClass: "dry", fireTest: "Fire endurance test not required" },
    { id: "fw_cooling", group: "Fresh water", system: "Cooling water system", allowed: { pipeUnions: true, compression: true, slipOn: true }, pipeSystemClass: "wet", fireTest: "30 min wet (*)", notes: ["Note 4"] },
    { id: "fw_condensate_return", group: "Fresh water", system: "Condensate return", allowed: { pipeUnions: true, compression: true, slipOn: true }, pipeSystemClass: "wet", fireTest: "30 min wet (*)", notes: ["Note 4"] },
    { id: "fw_non_essential", group: "Fresh water", system: "Non-essential system", allowed: { pipeUnions: true, compression: true, slipOn: true }, pipeSystemClass: "dry", fireTest: "Fire endurance test not required" },
    { id: "san_deck_drains_internal", group: "Sanitary / drains / scuppers", system: "Deck drains (internal)", allowed: { pipeUnions: true, compression: true, slipOn: true }, pipeSystemClass: "dry", fireTest: "Fire endurance test not required", notes: ["Note 5"], remarks: "Fire endurance test not required." },
    { id: "san_sanitary_drains", group: "Sanitary / drains / scuppers", system: "Sanitary drains", allowed: { pipeUnions: true, compression: true, slipOn: true }, pipeSystemClass: "dry", fireTest: "Fire endurance test not required" },
    { id: "san_scuppers_overboard", group: "Sanitary / drains / scuppers", system: "Scuppers and discharge (overboard)", allowed: { pipeUnions: true, compression: true, slipOn: false }, pipeSystemClass: "dry", fireTest: "Fire endurance test not required" },
    { id: "sv_water_tanks_dry_spaces", group: "Sounding / vent", system: "Water tanks / dry spaces", allowed: { pipeUnions: true, compression: true, slipOn: true }, pipeSystemClass: "dry, wet", fireTest: "Fire endurance test not required" },
    { id: "sv_oil_tanks_gt60", group: "Sounding / vent", system: "Oil tanks (fp > 60°C)", allowed: { pipeUnions: true, compression: true, slipOn: true }, pipeSystemClass: "dry", fireTest: "Fire endurance test not required", notes: ["Notes 2 & 3"] },
    { id: "misc_starting_control_air", group: "Miscellaneous", system: "Starting / control air", allowed: { pipeUnions: true, compression: true, slipOn: false }, pipeSystemClass: "dry", fireTest: "30 min dry (*)", notes: ["Note 4"] },
    { id: "misc_service_air_non_essential", group: "Miscellaneous", system: "Service air (non-essential)", allowed: { pipeUnions: true, compression: true, slipOn: true }, pipeSystemClass: "dry", fireTest: "Fire endurance test not required" },
    { id: "misc_brine", group: "Miscellaneous", system: "Brine", allowed: { pipeUnions: true, compression: true, slipOn: true }, pipeSystemClass: "wet", fireTest: "30 min wet (*)" },
    { id: "misc_co2_outside_protected", group: "Miscellaneous", system: "CO₂ system (outside protected space)", allowed: { pipeUnions: true, compression: true, slipOn: false }, pipeSystemClass: "dry", fireTest: "30 min dry (*)" },
    { id: "misc_co2_inside_protected", group: "Miscellaneous", system: "CO₂ system (inside protected space)", allowed: { pipeUnions: true, compression: true, slipOn: false }, pipeSystemClass: "dry", fireTest: "Fire endurance test not required", notes: ["See Note 8"] },
    { id: "misc_steam", group: "Miscellaneous", system: "Steam", allowed: { pipeUnions: true, compression: true, slipOn: false }, pipeSystemClass: "wet", fireTest: "Fire endurance test not required", notes: ["Note 6"] },
  ],
};
